// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"encoding/json"
	"github.com/ansrivas/fiberprometheus/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"latipe-transaction-service/config"
	"latipe-transaction-service/internal/cronjob"
	"latipe-transaction-service/internal/domain/repos"
	createPurchase2 "latipe-transaction-service/internal/publisher/createPurchase"
	"latipe-transaction-service/internal/service/orderserv"
	"latipe-transaction-service/internal/subscriber/createPurchase"
	"latipe-transaction-service/pkgs/db/mongodb"
	"latipe-transaction-service/pkgs/rabbitclient"
)

// Injectors from server.go:

func New() (*Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mongoClient, err := mongodb.OpenMongoDBConnection(configConfig)
	if err != nil {
		return nil, err
	}
	transactionRepository := repos.NewTransactionRepository(mongoClient)
	connection := rabbitclient.NewRabbitClientConnection(configConfig)
	orderOrchestratorPub := createPurchase2.NewOrderOrchestratorPub(configConfig, connection)
	orderService := orderserv.NewOrderService(transactionRepository, orderOrchestratorPub)
	purchaseReplySubscriber := createPurchase.NewPurchaseSubscriberReply(configConfig, orderService, connection)
	purchaseCreateOrchestratorSubscriber := createPurchase.NewPurchaseCreateOrchestratorSubscriber(configConfig, orderService, connection)
	cron := cronjob.NewCronInstance()
	checkingTxStatusCronJ := cronjob.NewCheckingTxStatusCronJ(configConfig, cron, orderService)
	server := NewServer(configConfig, purchaseReplySubscriber, purchaseCreateOrchestratorSubscriber, checkingTxStatusCronJ)
	return server, nil
}

// server.go:

type Server struct {
	app               *fiber.App
	globalCfg         *config.Config
	purchaseReplySub  *createPurchase.PurchaseReplySubscriber
	purchaseCreateSub *createPurchase.PurchaseCreateOrchestratorSubscriber
	checkTxStatus     *cronjob.CheckingTxStatusCronJ
}

func (serv Server) App() *fiber.App {
	return serv.app
}

func (serv Server) Config() *config.Config {
	return serv.globalCfg
}

func (serv Server) PurchaseReplySub() *createPurchase.PurchaseReplySubscriber {
	return serv.purchaseReplySub
}

func (serv Server) PurchaseCreateSub() *createPurchase.PurchaseCreateOrchestratorSubscriber {
	return serv.purchaseCreateSub
}

func (serv Server) CheckTxStatusCron() *cronjob.CheckingTxStatusCronJ {
	return serv.checkTxStatus
}

func NewServer(
	cfg *config.Config,
	purchaseReplySub *createPurchase.PurchaseReplySubscriber,
	purchaseCreateSub *createPurchase.PurchaseCreateOrchestratorSubscriber,
	checkTxStatus *cronjob.CheckingTxStatusCronJ) *Server {

	app := fiber.New(fiber.Config{
		ReadTimeout:  cfg.Server.ReadTimeout,
		WriteTimeout: cfg.Server.WriteTimeout,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
	})

	prometheus := fiberprometheus.New("latipe-order-service-v2")
	prometheus.RegisterAt(app, "/metrics")
	app.Use(prometheus.Middleware)

	app.Use(logger.New())

	app.Get("", func(ctx *fiber.Ctx) error {
		s := struct {
			Message string `json:"message"`
			Version string `json:"version"`
		}{
			Message: "transaction service was developed by TienDat",
			Version: "v1.0.0",
		}
		return ctx.JSON(s)
	})

	return &Server{
		globalCfg:         cfg,
		app:               app,
		purchaseReplySub:  purchaseReplySub,
		purchaseCreateSub: purchaseCreateSub,
		checkTxStatus:     checkTxStatus,
	}
}
